import type { Startup } from "@/types";

export const mockStartups: Startup[] = [
  {
    id: "startup-1",
    name: "NeuralShift AI",
    logo: "NS",
    tagline: "Enterprise AI that actually understands your business",
    description:
      "NeuralShift AI builds adaptive machine learning platforms that learn from enterprise workflows to automate complex decision-making. Their proprietary neural architecture reduces model training time by 80% while maintaining state-of-the-art accuracy across NLP, computer vision, and predictive analytics tasks.",
    website: "https://neuralshift.ai",
    founded: 2021,
    employees: 85,
    location: "San Francisco, CA",
    industries: ["AI/ML", "Enterprise Software"],
    technologies: ["Python", "PyTorch", "Kubernetes", "React", "GraphQL"],
    fundingStage: "Series B",
    totalFunding: 42_000_000,
    team: [
      { name: "Dr. Sarah Chen", role: "CEO & Co-Founder", avatar: "SC", linkedin: "https://linkedin.com/in/sarahchen" },
      { name: "Marcus Williams", role: "CTO & Co-Founder", avatar: "MW", linkedin: "https://linkedin.com/in/marcuswilliams" },
      { name: "Priya Patel", role: "VP Engineering", avatar: "PP" },
    ],
    metrics: { revenue: 8_500_000, revenueGrowth: 185, customers: 45, nps: 72, burnRate: 850_000, runway: 18 },
    aiAnalysis: {
      matchScore: 95,
      confidence: 92,
      strengths: [
        "Proprietary neural architecture with 80% faster training times",
        "Strong enterprise customer base with 45 logos including 3 Fortune 500",
        "185% YoY revenue growth demonstrating product-market fit",
        "Experienced founding team with ML research backgrounds",
      ],
      weaknesses: [
        "High burn rate relative to revenue",
        "Concentrated customer base in financial services",
        "Complex deployment requiring dedicated customer success",
      ],
      opportunities: [
        "Expanding into healthcare and manufacturing verticals",
        "Platform play enabling third-party model marketplace",
        "Federal government AI modernization contracts",
      ],
      risks: [
        "Competition from hyperscalers (AWS, Azure, GCP) with similar offerings",
        "Key person dependency on founding team for technical direction",
        "Regulatory uncertainty around enterprise AI governance",
      ],
      synergySummary:
        "NeuralShift AI is an exceptional match with strong technology alignment, proven enterprise traction, and a platform approach that enables deep integration. Their adaptive ML architecture directly addresses the need for automated workflow intelligence.",
      radarScores: [
        { dimension: "Technology Fit", score: 95, benchmark: 70 },
        { dimension: "Market Alignment", score: 90, benchmark: 65 },
        { dimension: "Team Strength", score: 92, benchmark: 72 },
        { dimension: "Financial Health", score: 78, benchmark: 68 },
        { dimension: "Innovation Score", score: 96, benchmark: 60 },
        { dimension: "Scalability", score: 88, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-2",
    name: "QuantumLedger",
    logo: "QL",
    tagline: "Next-gen blockchain infrastructure for enterprise finance",
    description:
      "QuantumLedger provides quantum-resistant blockchain infrastructure for financial institutions. Their layer-2 solution processes 50,000+ TPS while maintaining full regulatory compliance with SOC 2 and ISO 27001 certifications.",
    website: "https://quantumledger.io",
    founded: 2020,
    employees: 120,
    location: "New York, NY",
    industries: ["FinTech", "Blockchain"],
    technologies: ["Rust", "Solidity", "Go", "React", "PostgreSQL"],
    fundingStage: "Series B",
    totalFunding: 55_000_000,
    team: [
      { name: "James Park", role: "CEO & Founder", avatar: "JP", linkedin: "https://linkedin.com/in/jamespark" },
      { name: "Dr. Elena Kozlov", role: "CTO", avatar: "EK" },
      { name: "David Okonkwo", role: "Head of Compliance", avatar: "DO" },
    ],
    metrics: { revenue: 12_000_000, revenueGrowth: 140, customers: 28, nps: 68, burnRate: 1_200_000, runway: 15 },
    aiAnalysis: {
      matchScore: 88,
      confidence: 85,
      strengths: [
        "Quantum-resistant cryptography future-proofs the platform",
        "50,000+ TPS throughput outperforms most enterprise blockchain solutions",
        "SOC 2 and ISO 27001 certified, meeting stringent compliance requirements",
        "Strong revenue base with $12M ARR from 28 financial institutions",
      ],
      weaknesses: [
        "High burn rate with $1.2M/month spend",
        "Complex regulatory landscape across jurisdictions",
        "Enterprise sales cycle averages 9-12 months",
      ],
      opportunities: [
        "Central bank digital currency (CBDC) infrastructure partnerships",
        "Cross-border payment settlement market ($156T annually)",
        "Tokenized asset management and custody services",
      ],
      risks: [
        "Regulatory crackdown on blockchain/crypto in key markets",
        "Quantum computing timeline uncertainty affecting value proposition",
        "Competition from traditional financial infrastructure modernization",
      ],
      synergySummary:
        "QuantumLedger offers robust blockchain infrastructure with strong compliance credentials. Their quantum-resistant approach is forward-thinking, and the financial institution customer base validates enterprise readiness.",
      radarScores: [
        { dimension: "Technology Fit", score: 85, benchmark: 70 },
        { dimension: "Market Alignment", score: 82, benchmark: 65 },
        { dimension: "Team Strength", score: 88, benchmark: 72 },
        { dimension: "Financial Health", score: 75, benchmark: 68 },
        { dimension: "Innovation Score", score: 92, benchmark: 60 },
        { dimension: "Scalability", score: 90, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-3",
    name: "MedVault",
    logo: "MV",
    tagline: "AI-powered health data platform saving lives through insights",
    description:
      "MedVault aggregates and analyzes health data from EHRs, wearables, and genomic databases to provide predictive patient outcomes. Their FDA-cleared algorithms have demonstrated 40% improvement in early disease detection across partner hospital networks.",
    website: "https://medvault.health",
    founded: 2019,
    employees: 150,
    location: "Boston, MA",
    industries: ["HealthTech", "AI/ML"],
    technologies: ["Python", "TensorFlow", "FHIR", "AWS", "React Native"],
    fundingStage: "Series C",
    totalFunding: 78_000_000,
    team: [
      { name: "Dr. Amanda Torres", role: "CEO & Co-Founder", avatar: "AT", linkedin: "https://linkedin.com/in/amandatorres" },
      { name: "Dr. Raj Mehta", role: "Chief Medical Officer", avatar: "RM" },
      { name: "Lisa Chang", role: "CTO", avatar: "LC" },
    ],
    metrics: { revenue: 18_000_000, revenueGrowth: 95, customers: 32, nps: 78, burnRate: 1_500_000, runway: 22 },
    aiAnalysis: {
      matchScore: 92,
      confidence: 90,
      strengths: [
        "FDA-cleared algorithms with clinical validation across 12 hospital systems",
        "40% improvement in early disease detection is a compelling clinical outcome",
        "HIPAA-compliant data platform with enterprise security credentials",
        "Strong management team with deep healthcare domain expertise",
      ],
      weaknesses: [
        "Long regulatory approval cycles for new algorithm deployments",
        "Healthcare system integration complexity and legacy EHR challenges",
        "Premium pricing limits adoption in smaller healthcare facilities",
      ],
      opportunities: [
        "Expansion into pharmaceutical R&D data partnerships",
        "Remote patient monitoring and telehealth integration",
        "International expansion to NHS and EU healthcare systems",
      ],
      risks: [
        "HIPAA and data privacy regulation changes",
        "EHR vendor lock-in limiting data access",
        "Reimbursement model uncertainty for AI-assisted diagnostics",
      ],
      synergySummary:
        "MedVault represents a high-confidence match with FDA-cleared technology, strong clinical outcomes, and a sustainable business model. Their data platform approach creates significant value through network effects across the healthcare ecosystem.",
      radarScores: [
        { dimension: "Technology Fit", score: 90, benchmark: 70 },
        { dimension: "Market Alignment", score: 92, benchmark: 65 },
        { dimension: "Team Strength", score: 95, benchmark: 72 },
        { dimension: "Financial Health", score: 85, benchmark: 68 },
        { dimension: "Innovation Score", score: 88, benchmark: 60 },
        { dimension: "Scalability", score: 82, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-4",
    name: "GreenGrid Solutions",
    logo: "GG",
    tagline: "Smart energy management for a carbon-neutral future",
    description:
      "GreenGrid Solutions provides AI-driven energy management systems for commercial and industrial buildings. Their platform optimizes energy consumption in real-time, reducing costs by 25-40% while tracking and reporting carbon emissions for ESG compliance.",
    website: "https://greengrid.solutions",
    founded: 2020,
    employees: 65,
    location: "Austin, TX",
    industries: ["CleanTech", "IoT"],
    technologies: ["Python", "TensorFlow", "IoT", "React", "TimescaleDB"],
    fundingStage: "Series A",
    totalFunding: 18_000_000,
    team: [
      { name: "Michael Torres", role: "CEO & Founder", avatar: "MT", linkedin: "https://linkedin.com/in/michaeltorres" },
      { name: "Dr. Kim Yoon", role: "Chief Scientist", avatar: "KY" },
    ],
    metrics: { revenue: 4_200_000, revenueGrowth: 120, customers: 78, nps: 65, burnRate: 450_000, runway: 14 },
    aiAnalysis: {
      matchScore: 78,
      confidence: 75,
      strengths: [
        "25-40% energy cost reduction with measurable ROI for customers",
        "Strong growth trajectory with 120% YoY revenue increase",
        "ESG compliance reporting meets growing regulatory requirements",
      ],
      weaknesses: [
        "Hardware dependency for IoT sensor deployment adds complexity",
        "Limited international presence outside North America",
        "Competitive market with established energy management players",
        "Moderate runway requiring potential bridge funding",
      ],
      opportunities: [
        "EU Green Deal creating mandatory energy reporting requirements",
        "Expansion into residential smart energy management",
        "Carbon credit marketplace integration",
      ],
      risks: [
        "Energy price volatility affecting customer ROI calculations",
        "Supply chain issues for IoT hardware components",
        "Regulatory fragmentation across different markets",
      ],
      synergySummary:
        "GreenGrid Solutions offers proven energy management technology with strong customer ROI. The CleanTech focus aligns with growing ESG mandates, though the hardware dependency and competitive landscape present moderate risks.",
      radarScores: [
        { dimension: "Technology Fit", score: 72, benchmark: 70 },
        { dimension: "Market Alignment", score: 80, benchmark: 65 },
        { dimension: "Team Strength", score: 70, benchmark: 72 },
        { dimension: "Financial Health", score: 68, benchmark: 68 },
        { dimension: "Innovation Score", score: 75, benchmark: 60 },
        { dimension: "Scalability", score: 72, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-5",
    name: "CyberSentinel",
    logo: "CS",
    tagline: "AI-first threat detection for the modern enterprise",
    description:
      "CyberSentinel provides autonomous threat detection and response using behavioral AI that learns normal network patterns and identifies anomalies in real-time. Their platform processes 10B+ events daily and has prevented $2.3B in potential breaches across their customer base.",
    website: "https://cybersentinel.io",
    founded: 2019,
    employees: 200,
    location: "Washington, DC",
    industries: ["Cybersecurity", "AI/ML"],
    technologies: ["Go", "Python", "Kafka", "Elasticsearch", "React"],
    fundingStage: "Series C",
    totalFunding: 95_000_000,
    team: [
      { name: "Col. (Ret.) Robert Hayes", role: "CEO", avatar: "RH", linkedin: "https://linkedin.com/in/roberthayes" },
      { name: "Dr. Natasha Volkov", role: "CTO", avatar: "NV" },
      { name: "Tom Richardson", role: "VP Sales", avatar: "TR" },
    ],
    metrics: { revenue: 28_000_000, revenueGrowth: 110, customers: 95, nps: 74, burnRate: 2_000_000, runway: 20 },
    aiAnalysis: {
      matchScore: 85,
      confidence: 88,
      strengths: [
        "Processing 10B+ events daily demonstrates enterprise-grade scalability",
        "$2.3B in prevented breaches provides compelling customer evidence",
        "Strong government and defense sector relationships",
        "110% revenue growth with healthy unit economics",
      ],
      weaknesses: [
        "High burn rate at $2M/month requires continued growth",
        "Government sector sales cycles are lengthy and unpredictable",
        "Competitive landscape includes well-funded incumbents like CrowdStrike",
      ],
      opportunities: [
        "Zero Trust architecture adoption driving security platform demand",
        "OT/ICS security for critical infrastructure protection",
        "International expansion to Five Eyes intelligence partners",
      ],
      risks: [
        "Cybersecurity talent war driving up personnel costs",
        "Government budget sequestration risk",
        "False positive rates affecting customer trust",
      ],
      synergySummary:
        "CyberSentinel is a strong match with proven AI-first security capabilities and impressive scale. Their government sector expertise and prevention track record validate the technology, though competitive dynamics require monitoring.",
      radarScores: [
        { dimension: "Technology Fit", score: 82, benchmark: 70 },
        { dimension: "Market Alignment", score: 85, benchmark: 65 },
        { dimension: "Team Strength", score: 90, benchmark: 72 },
        { dimension: "Financial Health", score: 80, benchmark: 68 },
        { dimension: "Innovation Score", score: 78, benchmark: 60 },
        { dimension: "Scalability", score: 88, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-6",
    name: "EduSpark",
    logo: "ES",
    tagline: "Personalized learning at scale with AI tutoring",
    description:
      "EduSpark provides an AI-powered adaptive learning platform that personalizes educational content for corporate training and higher education. Their system uses cognitive science principles to optimize knowledge retention, achieving 3x faster skill acquisition compared to traditional methods.",
    website: "https://eduspark.io",
    founded: 2021,
    employees: 45,
    location: "London, UK",
    industries: ["EdTech", "AI/ML"],
    technologies: ["TypeScript", "Next.js", "Python", "OpenAI", "PostgreSQL"],
    fundingStage: "Series A",
    totalFunding: 12_000_000,
    team: [
      { name: "Dr. Emily Watson", role: "CEO & Co-Founder", avatar: "EW", linkedin: "https://linkedin.com/in/emilywatson" },
      { name: "Amir Hassan", role: "CTO & Co-Founder", avatar: "AH" },
    ],
    metrics: { revenue: 2_800_000, revenueGrowth: 90, customers: 120, nps: 71, burnRate: 350_000, runway: 12 },
    aiAnalysis: {
      matchScore: 72,
      confidence: 70,
      strengths: [
        "3x faster skill acquisition validated by third-party studies",
        "120 customers including several enterprise accounts",
        "Cognitive science-based approach differentiates from competitors",
      ],
      weaknesses: [
        "Limited runway at 12 months requires near-term fundraising",
        "Content creation dependency for new subject areas",
        "Small team with limited enterprise sales capacity",
        "Revenue concentration in UK market",
      ],
      opportunities: [
        "Corporate upskilling market growing at 15% CAGR",
        "Partnership with LMS providers for embedded integration",
        "Expansion into US market through enterprise partnerships",
      ],
      risks: [
        "LLM commoditization reducing differentiation of AI tutoring",
        "Enterprise budget cuts for training during economic downturns",
        "Regulatory requirements for educational content in different markets",
      ],
      synergySummary:
        "EduSpark has a solid product with validated learning outcomes, but faces challenges with limited runway and market concentration. The corporate training angle is promising, though competitive dynamics from LLM-native solutions are intensifying.",
      radarScores: [
        { dimension: "Technology Fit", score: 68, benchmark: 70 },
        { dimension: "Market Alignment", score: 72, benchmark: 65 },
        { dimension: "Team Strength", score: 75, benchmark: 72 },
        { dimension: "Financial Health", score: 58, benchmark: 68 },
        { dimension: "Innovation Score", score: 70, benchmark: 60 },
        { dimension: "Scalability", score: 65, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-7",
    name: "DataWeave",
    logo: "DW",
    tagline: "Real-time data fabric for the modern enterprise",
    description:
      "DataWeave provides a real-time data integration and analytics platform that creates a unified data fabric across cloud, on-premise, and edge environments. Their zero-copy architecture eliminates data duplication while providing sub-second query performance across petabyte-scale datasets.",
    website: "https://dataweave.tech",
    founded: 2020,
    employees: 110,
    location: "Seattle, WA",
    industries: ["Data Analytics", "Enterprise Software"],
    technologies: ["Rust", "Apache Arrow", "Kubernetes", "React", "gRPC"],
    fundingStage: "Series B",
    totalFunding: 48_000_000,
    team: [
      { name: "Alex Rivera", role: "CEO & Co-Founder", avatar: "AR", linkedin: "https://linkedin.com/in/alexrivera" },
      { name: "Dr. Yuki Tanaka", role: "CTO & Co-Founder", avatar: "YT" },
      { name: "Jennifer Liu", role: "VP Product", avatar: "JL" },
    ],
    metrics: { revenue: 14_000_000, revenueGrowth: 160, customers: 52, nps: 76, burnRate: 1_100_000, runway: 16 },
    aiAnalysis: {
      matchScore: 91,
      confidence: 89,
      strengths: [
        "Zero-copy architecture is a genuine technical innovation reducing infrastructure costs",
        "Sub-second queries on petabyte-scale data sets a new performance benchmark",
        "160% revenue growth with strong net revenue retention of 135%",
        "Founding team includes former principal engineers from Snowflake and Databricks",
      ],
      weaknesses: [
        "Requires sophisticated data engineering teams for optimal deployment",
        "Competition from well-funded data platform unicorns",
        "Complex pricing model can slow enterprise procurement",
      ],
      opportunities: [
        "Real-time AI/ML feature stores for production ML pipelines",
        "Data mesh architecture adoption driving federated data platform demand",
        "Expansion into data governance and compliance tooling",
      ],
      risks: [
        "Hyperscaler competition with integrated data services",
        "Open-source alternatives (Apache Iceberg, Delta Lake) commoditizing features",
        "Economic downturn reducing enterprise data infrastructure spending",
      ],
      synergySummary:
        "DataWeave is an excellent match with innovative data infrastructure technology, strong growth metrics, and a world-class founding team. Their zero-copy architecture and real-time capabilities directly address modern enterprise data challenges.",
      radarScores: [
        { dimension: "Technology Fit", score: 92, benchmark: 70 },
        { dimension: "Market Alignment", score: 88, benchmark: 65 },
        { dimension: "Team Strength", score: 94, benchmark: 72 },
        { dimension: "Financial Health", score: 82, benchmark: 68 },
        { dimension: "Innovation Score", score: 95, benchmark: 60 },
        { dimension: "Scalability", score: 90, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-8",
    name: "AeroLogic",
    logo: "AL",
    tagline: "AI-powered logistics optimization for global supply chains",
    description:
      "AeroLogic uses machine learning to optimize last-mile delivery, warehouse operations, and supply chain routing. Their platform reduces logistics costs by 30% and delivery times by 25% through real-time demand forecasting and dynamic route optimization.",
    website: "https://aerologic.co",
    founded: 2020,
    employees: 90,
    location: "Chicago, IL",
    industries: ["Logistics", "AI/ML"],
    technologies: ["Python", "Java", "Kafka", "React", "MongoDB"],
    fundingStage: "Series A",
    totalFunding: 22_000_000,
    team: [
      { name: "Carlos Mendez", role: "CEO & Founder", avatar: "CM", linkedin: "https://linkedin.com/in/carlosmendez" },
      { name: "Dr. Wei Zhang", role: "Chief AI Officer", avatar: "WZ" },
      { name: "Sarah O'Brien", role: "COO", avatar: "SO" },
    ],
    metrics: { revenue: 6_500_000, revenueGrowth: 130, customers: 35, nps: 69, burnRate: 600_000, runway: 13 },
    aiAnalysis: {
      matchScore: 82,
      confidence: 78,
      strengths: [
        "30% cost reduction and 25% faster deliveries validated across 35 customers",
        "Real-time optimization engine handles 100K+ routing decisions per hour",
        "Strong growth at 130% YoY with expanding customer base",
      ],
      weaknesses: [
        "Moderate runway at 13 months requiring fundraising attention",
        "Integration complexity with legacy warehouse management systems",
        "Customer concentration in mid-market e-commerce",
        "Limited international logistics network coverage",
      ],
      opportunities: [
        "Autonomous vehicle integration for last-mile delivery",
        "Sustainability-focused routing for carbon-neutral logistics",
        "Expansion into cold chain logistics for pharmaceuticals and food",
      ],
      risks: [
        "Amazon Logistics building similar capabilities in-house",
        "Fuel price volatility affecting customer ROI projections",
        "Labor market disruptions affecting warehouse operations",
      ],
      synergySummary:
        "AeroLogic demonstrates strong product-market fit in logistics optimization with measurable customer outcomes. The AI-driven approach is differentiated, though competitive pressure from Amazon and limited international coverage are notable considerations.",
      radarScores: [
        { dimension: "Technology Fit", score: 80, benchmark: 70 },
        { dimension: "Market Alignment", score: 78, benchmark: 65 },
        { dimension: "Team Strength", score: 82, benchmark: 72 },
        { dimension: "Financial Health", score: 72, benchmark: 68 },
        { dimension: "Innovation Score", score: 80, benchmark: 60 },
        { dimension: "Scalability", score: 76, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-9",
    name: "BioSync",
    logo: "BS",
    tagline: "Computational biology platform accelerating drug discovery",
    description:
      "BioSync uses AI-driven computational biology to accelerate drug discovery timelines from years to months. Their molecular simulation platform has identified 3 promising drug candidates currently in pre-clinical trials for rare diseases.",
    website: "https://biosync.bio",
    founded: 2019,
    employees: 55,
    location: "Cambridge, MA",
    industries: ["Biotech", "AI/ML"],
    technologies: ["Python", "JAX", "CUDA", "React", "Neo4j"],
    fundingStage: "Series A",
    totalFunding: 25_000_000,
    team: [
      { name: "Dr. Rachel Kim", role: "CEO & Co-Founder", avatar: "RK", linkedin: "https://linkedin.com/in/rachelkim" },
      { name: "Dr. Thomas Berg", role: "CSO & Co-Founder", avatar: "TB" },
    ],
    metrics: { revenue: 1_500_000, revenueGrowth: 45, customers: 8, nps: 82, burnRate: 700_000, runway: 16 },
    aiAnalysis: {
      matchScore: 68,
      confidence: 65,
      strengths: [
        "3 drug candidates in pre-clinical trials demonstrate platform validity",
        "Exceptional NPS of 82 indicates strong customer satisfaction",
        "World-class scientific team with 50+ published papers",
      ],
      weaknesses: [
        "Low revenue and slow growth typical of biotech timelines",
        "Very small customer base of 8 pharmaceutical partners",
        "High burn rate relative to revenue generation",
        "Long time-to-value for drug discovery customers",
      ],
      opportunities: [
        "Rare disease drug development has favorable regulatory fast-track pathways",
        "Licensing revenue from successful drug candidates",
        "Platform expansion to agriculture and materials science",
      ],
      risks: [
        "Drug candidate failure in clinical trials",
        "Regulatory approval uncertainty and timeline risk",
        "Biotech funding environment volatility",
        "Competition from established pharma AI labs",
      ],
      synergySummary:
        "BioSync has impressive scientific credentials and a promising pipeline, but the biotech business model introduces significant timeline and outcome uncertainty. Best suited for organizations with long-term innovation horizons and risk tolerance.",
      radarScores: [
        { dimension: "Technology Fit", score: 65, benchmark: 70 },
        { dimension: "Market Alignment", score: 58, benchmark: 65 },
        { dimension: "Team Strength", score: 85, benchmark: 72 },
        { dimension: "Financial Health", score: 52, benchmark: 68 },
        { dimension: "Innovation Score", score: 88, benchmark: 60 },
        { dimension: "Scalability", score: 55, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-10",
    name: "CloudNest",
    logo: "CN",
    tagline: "Multi-cloud infrastructure management made simple",
    description:
      "CloudNest provides a unified control plane for managing multi-cloud infrastructure across AWS, Azure, GCP, and private clouds. Their platform automates cost optimization, security compliance, and infrastructure scaling, saving enterprise customers an average of 35% on cloud spend.",
    website: "https://cloudnest.dev",
    founded: 2020,
    employees: 130,
    location: "Berlin, Germany",
    industries: ["Cloud Infrastructure", "DevOps"],
    technologies: ["Go", "Terraform", "Kubernetes", "React", "ClickHouse"],
    fundingStage: "Series B",
    totalFunding: 52_000_000,
    team: [
      { name: "Friedrich Mueller", role: "CEO & Co-Founder", avatar: "FM", linkedin: "https://linkedin.com/in/friedrichmueller" },
      { name: "Anna Kowalski", role: "CTO & Co-Founder", avatar: "AK" },
      { name: "Ben Thompson", role: "VP Sales", avatar: "BT" },
    ],
    metrics: { revenue: 16_000_000, revenueGrowth: 150, customers: 68, nps: 73, burnRate: 1_300_000, runway: 17 },
    aiAnalysis: {
      matchScore: 89,
      confidence: 86,
      strengths: [
        "35% average cloud cost savings provides immediate and measurable ROI",
        "Unified control plane across all major cloud providers is a differentiated offering",
        "150% revenue growth with 68 enterprise customers validates demand",
        "Strong European presence with GDPR-compliant architecture",
      ],
      weaknesses: [
        "Rapid expansion straining engineering resources",
        "US market penetration still early stage",
        "Dependency on cloud provider APIs that can change",
      ],
      opportunities: [
        "FinOps category growth as cloud spending scrutiny increases",
        "Integration with AI/ML infrastructure management",
        "Government cloud compliance automation for FedRAMP/IL5",
      ],
      risks: [
        "Cloud providers building native multi-cloud management tools",
        "Open-source alternatives gaining enterprise traction",
        "Economic downturn reducing cloud migration budgets",
      ],
      synergySummary:
        "CloudNest is a high-confidence match with proven cost optimization capabilities and strong multi-cloud coverage. Their European base provides GDPR expertise, and the 150% growth rate signals strong market pull.",
      radarScores: [
        { dimension: "Technology Fit", score: 88, benchmark: 70 },
        { dimension: "Market Alignment", score: 86, benchmark: 65 },
        { dimension: "Team Strength", score: 85, benchmark: 72 },
        { dimension: "Financial Health", score: 82, benchmark: 68 },
        { dimension: "Innovation Score", score: 84, benchmark: 60 },
        { dimension: "Scalability", score: 92, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-11",
    name: "RetailPulse",
    logo: "RP",
    tagline: "In-store analytics powered by computer vision",
    description:
      "RetailPulse uses computer vision and IoT sensors to provide real-time in-store analytics for brick-and-mortar retailers. Their platform tracks foot traffic, dwell times, and conversion rates, helping retailers optimize store layouts and staffing.",
    website: "https://retailpulse.ai",
    founded: 2022,
    employees: 30,
    location: "Atlanta, GA",
    industries: ["RetailTech", "AI/ML"],
    technologies: ["Python", "OpenCV", "Edge Computing", "React", "Redis"],
    fundingStage: "Seed",
    totalFunding: 5_500_000,
    team: [
      { name: "Diana Foster", role: "CEO & Founder", avatar: "DF", linkedin: "https://linkedin.com/in/dianafoster" },
      { name: "Kevin Park", role: "CTO", avatar: "KP" },
    ],
    metrics: { revenue: 900_000, revenueGrowth: 75, customers: 42, nps: 62, burnRate: 250_000, runway: 8 },
    aiAnalysis: {
      matchScore: 58,
      confidence: 62,
      strengths: [
        "42 retail location deployments demonstrate repeatable sales motion",
        "Computer vision approach provides unique in-store insights",
        "Low-cost IoT hardware makes solution accessible to SMB retailers",
      ],
      weaknesses: [
        "Limited runway at 8 months requiring near-term fundraising",
        "Retail industry facing structural headwinds from e-commerce",
        "Privacy concerns around in-store customer tracking",
        "Small team with key person dependencies",
      ],
      opportunities: [
        "Expansion into smart shelf and inventory management",
        "Partnership with POS system providers for integrated analytics",
        "International expansion to Asian retail markets",
      ],
      risks: [
        "Privacy regulation affecting data collection practices",
        "Retail recession impacting technology spending",
        "Competition from established retail analytics providers",
        "Hardware supply chain dependencies",
      ],
      synergySummary:
        "RetailPulse has interesting technology but faces headwinds in the traditional retail sector. The limited runway and small team create execution risk. Best suited as a niche solution for specific retail verticals.",
      radarScores: [
        { dimension: "Technology Fit", score: 55, benchmark: 70 },
        { dimension: "Market Alignment", score: 50, benchmark: 65 },
        { dimension: "Team Strength", score: 60, benchmark: 72 },
        { dimension: "Financial Health", score: 48, benchmark: 68 },
        { dimension: "Innovation Score", score: 65, benchmark: 60 },
        { dimension: "Scalability", score: 58, benchmark: 66 },
      ],
    },
  },
  {
    id: "startup-12",
    name: "AgriSense",
    logo: "AS",
    tagline: "Precision agriculture powered by satellite AI",
    description:
      "AgriSense uses satellite imagery and machine learning to provide precision agriculture insights to farmers and agribusiness companies. Their platform monitors crop health, predicts yields, and optimizes irrigation and fertilization schedules across 2M+ acres.",
    website: "https://agrisense.farm",
    founded: 2021,
    employees: 35,
    location: "Des Moines, IA",
    industries: ["AgriTech", "AI/ML"],
    technologies: ["Python", "Satellite Imaging", "TensorFlow", "GIS", "React"],
    fundingStage: "Seed",
    totalFunding: 4_500_000,
    team: [
      { name: "Jake Morrison", role: "CEO & Co-Founder", avatar: "JM", linkedin: "https://linkedin.com/in/jakemorrison" },
      { name: "Dr. Mei Chen", role: "Chief Data Scientist", avatar: "MC" },
      { name: "Tom Bergstrom", role: "Head of Sales", avatar: "TB" },
    ],
    metrics: { revenue: 800_000, revenueGrowth: 60, customers: 85, nps: 58, burnRate: 200_000, runway: 8 },
    aiAnalysis: {
      matchScore: 45,
      confidence: 60,
      strengths: [
        "Covering 2M+ acres demonstrates scalable deployment model",
        "Satellite-based approach requires no on-farm hardware",
        "Strong domain expertise in agricultural science",
      ],
      weaknesses: [
        "Very limited runway requiring immediate fundraising",
        "Seasonal revenue pattern creates cash flow challenges",
        "Low willingness-to-pay in traditional farming sector",
        "Dependent on third-party satellite data providers",
      ],
      opportunities: [
        "Carbon credit verification for sustainable farming practices",
        "Insurance partnerships for crop risk assessment",
        "Government agricultural subsidy optimization",
      ],
      risks: [
        "Funding gap may force unfavorable terms or acquisition",
        "Climate volatility reducing prediction accuracy",
        "Competitor John Deere integrating similar capabilities",
        "Satellite data cost increases affecting margins",
      ],
      synergySummary:
        "AgriSense has a promising technology approach to precision agriculture, but significant financial and market challenges limit the near-term opportunity. The short runway and seasonal revenue model create urgency around the next funding round.",
      radarScores: [
        { dimension: "Technology Fit", score: 42, benchmark: 70 },
        { dimension: "Market Alignment", score: 40, benchmark: 65 },
        { dimension: "Team Strength", score: 55, benchmark: 72 },
        { dimension: "Financial Health", score: 35, benchmark: 68 },
        { dimension: "Innovation Score", score: 60, benchmark: 60 },
        { dimension: "Scalability", score: 48, benchmark: 66 },
      ],
    },
  },
];
